name: Testing
values:
  - key: SERVER_ADDRESS
    value: 'http://localhost'
  - key: SERVER_PORT
    value: '4000'
  - key: API_VERSION
    value: v1
  - key: TEST_CONSUMER_UUID_ACME
    value: 018f3a00-0000-7000-8000-000000000001
  - key: TEST_API_KEY_UUID_ACME
    value: 018f3a00-0000-7000-8000-000000000101
  - key: TEST_JOB_UUID_ACME
    value: 018f3a00-0000-7000-8000-000000000201
  - key: TEST_JOB_PUBLIC_UUID_ACME
    value: b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22
